name: ArthaGuard Alert Worker

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-worker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Alert Worker
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: python work.py
